### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by denouche** [GoogleCloudPlatform/js-data-cloud-datastore#3]
Hello,

I would like to update my nodejs version to >= 8, but I have a problem while installing this js-data plugin with NPM.

First
```
node-pre-gyp http 403 https://storage.googleapis.com/grpc-precompiled-binaries/node/grpc/v0.14.1/node-v57-linux-x64.tar.gz
node-pre-gyp ERR! Tried to download: https://storage.googleapis.com/grpc-precompiled-binaries/node/grpc/v0.14.1/node-v57-linux-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for grpc@0.14.1 and node@8.1.0 (node-v57 ABI) (falling back to source compile with node-gyp) 
```

The issue really looks like this one: https://github.com/GoogleCloudPlatform/google-cloud-node/issues/1753

And upgrading `@google-cloud/datastore` to last version seems to solve the problem.

Apparently I'm not the only one having this issue, because someone already forked your project in order to update dependencies: https://github.com/GoogleCloudPlatform/js-data-cloud-datastore/compare/master...stater:master

Thanks in advance!

**Comment by tswast** [comment]
@jmdobry Should we enable greenkeeper on this repo?

**Comment by denouche** [comment]
up ?

**Comment by tswast** [comment]
Thanks for the reminder. I've just added Greenkeeper to the repo. Hopefully it starts sending some PRs to update dependencies soon.

**Comment by tswast** [comment]
There's a PR started at https://github.com/GoogleCloudPlatform/js-data-cloud-datastore/pull/5 I got a bit stuck, though. I'm not really a maintainer a Node.js person so I got as far as I could.
